version: 2.1

orbs:
  orb-tools: circleci/orb-tools@2.0.2

jobs:
  push_latest_version_tag:
    docker:
      - image: circleci/ruby:2.5
    working_directory: ~/app
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "43:39:3a:d1:90:49:a4:85:db:17:41:ce:88:55:44:92"
      - run: curl -fLSs https://circle.ci/cli | sudo bash
      - run:
          name: Setup git
          command: |
            git config push.default current
            git config user.email "$EMAIL"
            git config user.name "CircleCI"
      - run: ruby .circleci/push_latest_version_tag.rb sue445/ruby-orbs

  smoke_test:
    # c.f. https://github.com/CircleCI-Public/artifactory-orb/blob/39e72bee4c884eae0adde4c3204f0e18d727bc4b/.circleci/config.yml
    docker:
      - image: circleci/node:10
    parameters:
      branch:
        type: string
        description: branch of circleci-ruby-orbs-test
    working_directory: ~/app
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
          - "43:39:3a:d1:90:49:a4:85:db:17:41:ce:88:55:44:92"
      - run: ./.circleci/setup_smoke_test.sh << parameters.branch >>

      - run:
          name: Poll for result
          no_output_timeout: 5m
          command: |
            export SMOKE_BRANCH="smoke_test/${CIRCLE_SHA1}_<< parameters.branch >>"
            echo "Smoke test branch: https://github.com/sue445/circleci-ruby-orbs-test/commits/${SMOKE_BRANCH}"

            curl https://circleci.com/api/v1.1/project/github/sue445/circleci-ruby-orbs-test/tree/${SMOKE_BRANCH}?limit=1 > build-result.json
            BUILD_URL=$(cat build-result.json | jq -r '.[0].build_url')
            echo "Monitoring Build: $BUILD_URL for status"
            while true; do
              curl https://circleci.com/api/v1.1/project/github/sue445/circleci-ruby-orbs-test/tree/${SMOKE_BRANCH}?limit=1 > build-result.json
              LIFECYCLE=$(cat build-result.json | jq -r '.[0].lifecycle')
              if [ "$LIFECYCLE" == "finished" ];then
                STATUS=$(cat build-result.json | jq -r '.[0].status')
                if [ "$STATUS" == "success" ];then
                  echo "Test project build successful."
                  exit 0
                else
                  exit 1
                fi
              else
                sleep 10
              fi
            done

workflows:
  version: 2

  # c.f. https://github.com/CircleCI-Public/hello-orb/blob/c43a73505b996c29688510b5d60d17130ae937b7/.circleci/config.yml
  btd:
    jobs:
      - orb-tools/pack:
          source-dir: src/
          destination-orb-path: packed/orb.yml
          workspace-path: packed/orb.yml
          artifact-path: packed/orb.yml

      - orb-tools/test-in-builds:
          orb-location: packed/orb.yml
          orb-name: ruby-orbs
          test-steps:
            - orb-tools/local-test-build:
                test-config-location: test/bundler-v1/bundle-install_test.yml
            - orb-tools/local-test-build:
                test-config-location: test/bundler-v1/bundle-install-gemspec_test.yml
            - orb-tools/local-test-build:
                test-config-location: test/bundler-v1/bundle-update-pr_test.yml
            - orb-tools/local-test-build:
                test-config-location: test/bundler-v2/bundle-install_test.yml
            - orb-tools/local-test-build:
                test-config-location: test/bundler-v2/bundle-install-gemspec_test.yml
            - orb-tools/local-test-build:
                test-config-location: test/bundler-v2/bundle-update-pr_test.yml
          attach-workspace: true
          checkout: true
          requires:
            - orb-tools/pack

      - orb-tools/publish:
          orb-path: packed/orb.yml
          orb-ref: "sue445/ruby-orbs@dev:${CIRCLE_SHA1}"
          publish-token-variable: "$CIRCLECI_API_TOKEN"
          attach-workspace: true
          checkout: false
          requires: [orb-tools/pack]

      - smoke_test:
          name: smoke_test (bundler v2.1)
          branch: master
          requires: [orb-tools/test-in-builds]

      - smoke_test:
          name: smoke_test (bundler v1.17)
          branch: bundler_1.17
          requires: [orb-tools/test-in-builds]

      - orb-tools/increment:
          orb-path: packed/orb.yml
          orb-ref: "sue445/ruby-orbs"
          segment: "patch"
          publish-token-variable: "$CIRCLECI_API_TOKEN"
          attach-workspace: true
          checkout: false
          requires: [orb-tools/test-in-builds]
          filters:
            branches:
              only: master

      - push_latest_version_tag:
          requires: [orb-tools/increment]
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/

  release:
    jobs:
      - orb-tools/pack:
          source-dir: src/
          destination-orb-path: packed/orb.yml
          workspace-path: packed/orb.yml
          artifact-path: packed/orb.yml
          filters:
            tags:
              only: /^[0-9.]+\.0$/
            branches:
              ignore: /.*/

      - orb-tools/publish:
          orb-path: packed/orb.yml
          orb-ref: "sue445/ruby-orbs@${CIRCLE_TAG}"
          publish-token-variable: "$CIRCLECI_API_TOKEN"
          attach-workspace: true
          checkout: false
          requires: [orb-tools/pack]
          filters:
            tags:
              only: /^[0-9.]+\.0$/
            branches:
              ignore: /.*/
