version: 2.1

orbs:
  orb-tools: circleci/orb-tools@2

jobs:
  validate:
    docker:
      - image: circleci/circleci-cli
    working_directory: ~/app
    steps:
      - checkout
      - run: circleci orb validate src/orb.yml

  smoke_test:
    # c.f. https://github.com/CircleCI-Public/artifactory-orb/blob/39e72bee4c884eae0adde4c3204f0e18d727bc4b/.circleci/config.yml
    docker:
      - image: circleci/node:10
    working_directory: ~/app
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
          - "43:39:3a:d1:90:49:a4:85:db:17:41:ce:88:55:44:92"
      - run: ./.circleci/setup_smoke_test.sh

      - run:
          name: Poll for result
          no_output_timeout: 5m
          command: |
            export SMOKE_BRANCH="smoke_test/${CIRCLE_SHA1}"
            echo "Smoke test branch: https://github.com/sue445/circleci-orb-bundle-install-test/commits/${SMOKE_BRANCH}"

            curl https://circleci.com/api/v1.1/project/github/sue445/circleci-orb-bundle-install-test/tree/${SMOKE_BRANCH}?limit=1 > build-result.json
            BUILD_URL=$(cat build-result.json | jq -r '.[0].build_url')
            echo "Monitoring Build: $BUILD_URL for status"
            while true; do
              curl https://circleci.com/api/v1.1/project/github/sue445/circleci-orb-bundle-install-test/tree/${SMOKE_BRANCH}?limit=1 > build-result.json
              LIFECYCLE=$(cat build-result.json | jq -r '.[0].lifecycle')
              if [ "$LIFECYCLE" == "finished" ];then
                STATUS=$(cat build-result.json | jq -r '.[0].status')
                if [ "$STATUS" == "success" ];then
                  echo "Test project build successful."
                  exit 0
                else
                  exit 1
                fi
              else
                sleep 10
              fi
            done

workflows:
  version: 2

  # c.f. https://github.com/CircleCI-Public/hello-orb/blob/c43a73505b996c29688510b5d60d17130ae937b7/.circleci/config.yml
  btd:
    jobs:
      - validate

      - orb-tools/pack:
          source-dir: src/
          destination-orb-path: packed/orb.yml
          workspace-path: packed/orb.yml
          artifact-path: packed/orb.yml
          requires:
            - validate

      - orb-tools/publish:
          orb-path: packed/orb.yml
          orb-ref: "sue445/bundle-install@dev:${CIRCLE_SHA1}"
          publish-token-variable: "$CIRCLECI_API_TOKEN"
          attach-workspace: true
          checkout: false
          requires: [orb-tools/pack]

      - smoke_test:
          requires: [orb-tools/publish]

#      - orb-tools/increment:
#          orb-path: packed/orb.yml
#          orb-ref: "sue445/bundle-install"
#          segment: "patch"
#          publish-token-variable: "$CIRCLECI_API_TOKEN"
#          attach-workspace: true
#          checkout: false
#          requires: [orb-tools/pack]
#          filters:
#            branches:
#              only: master

  release:
    jobs:
      - validate:
          filters:
            tags:
              only: /.*/

      - orb-tools/pack:
          source-dir: src/
          destination-orb-path: packed/orb.yml
          workspace-path: packed/orb.yml
          artifact-path: packed/orb.yml
          requires:
            - validate
          filters:
            tags:
              only: /.*/

      - orb-tools/publish:
          orb-path: packed/orb.yml
          orb-ref: "sue445/bundle-install@${CIRCLE_TAG}"
          publish-token-variable: "$CIRCLECI_API_TOKEN"
          attach-workspace: true
          checkout: false
          requires: [orb-tools/pack]
          filters:
            tags:
              only: /.*/
