version: 2.1

orbs:
  orb-tools: circleci/orb-tools@2

jobs:
  validate:
    docker:
      - image: circleci/circleci-cli
    working_directory: ~/app
    steps:
      - checkout
      - run: circleci orb validate src/orb.yml

workflows:
  version: 2

  build:
    jobs:
      - validate

  # c.f. https://github.com/CircleCI-Public/hello-orb/blob/c43a73505b996c29688510b5d60d17130ae937b7/.circleci/config.yml
  btd:
    jobs:
      - orb-tools/pack:
          source-dir: src/
          destination-orb-path: packed/orb.yml
          workspace-path: packed/orb.yml
          artifact-path: packed/orb.yml

      - orb-tools/publish:
          orb-path: packed/orb.yml
          orb-ref: "sue445/bundle-install@dev:${CIRCLE_BRANCH}"
          publish-token-variable: "$CIRCLECI_API_TOKEN"
          attach-workspace: true
          checkout: false
          requires: [orb-tools/pack]

      - orb-tools/increment:
          orb-path: packed/orb.yml
          orb-ref: "sue445/bundle-install"
          segment: "patch"
          publish-token-variable: "$CIRCLECI_API_TOKEN"
          attach-workspace: true
          checkout: false
          requires: [orb-tools/pack]
          filters:
            branches:
              only: master
